parameters:
    akyos_updates.ai_chat.openai_api_key: '%env(OPENAI_API_KEY)%'
    akyos_updates.ai_chat.openai_model: 'gpt-4-turbo-preview'

services:
    AkyosUpdates\AIChat\Prompt\PromptBuilder:
        arguments:
            $baseSystemPrompt: '' 
    AkyosUpdates\AIChat\Service\OpenAIService:
        arguments:
            $apiKey: '%akyos_updates.ai_chat.openai_api_key%'
            $model: '%akyos_updates.ai_chat.openai_model%'
    AkyosUpdates\AIChat\Service\ActionRegistryService:
        arguments:
            $taggedActions: !tagged_iterator ai.action
            $container: '@service_container'
    AkyosUpdates\AIChat\Utils\ToolSchemaGenerator:
        arguments:
            $actionRegistry: '@AkyosUpdates\AIChat\Service\ActionRegistryService'
    AkyosUpdates\AIChat\Service\IntentRouterService:
        arguments:
            $openAIService: '@AkyosUpdates\AIChat\Service\OpenAIService'
            $actionRegistry: '@AkyosUpdates\AIChat\Service\ActionRegistryService'
    AkyosUpdates\AIChat\Action\UpdateWordPressAction:
        tags: ['ai.action']