<?php

namespace ContainerUmgQ1Iw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAkyosUpdatesService extends AkyosUpdates_KernelDevDebugContainer
{
    /**
     * Gets the public 'AkyosUpdates\AkyosUpdates' shared autowired service.
     *
     * @return \AkyosUpdates\AkyosUpdates
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/AkyosUpdates.php';

        return $container->services['AkyosUpdates\\AkyosUpdates'] = new \AkyosUpdates\AkyosUpdates();
    }
}
