<?php

namespace ContainerUmgQ1Iw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHookService extends AkyosUpdates_KernelDevDebugContainer
{
    /**
     * Gets the public 'AkyosUpdates\Attribute\Hook' shared autowired service.
     *
     * @return \AkyosUpdates\Attribute\Hook
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Attribute/Hook.php';

        return $container->services['AkyosUpdates\\Attribute\\Hook'] = new \AkyosUpdates\Attribute\Hook();
    }
}
