<?php

namespace ContainerCXzNcDS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAkyosUpdatesControllerService extends AkyosUpdates_KernelDevDebugContainer
{
    /**
     * Gets the public 'AkyosUpdates\Controller\AkyosUpdatesController' shared autowired service.
     *
     * @return \AkyosUpdates\Controller\AkyosUpdatesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/service-contracts/ServiceSubscriberInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AkyosUpdatesController.php';

        $container->services['AkyosUpdates\\Controller\\AkyosUpdatesController'] = $instance = new \AkyosUpdates\Controller\AkyosUpdatesController();

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('AkyosUpdates\\Controller\\AkyosUpdatesController', $container));

        return $instance;
    }
}
