<?php

namespace ContainerCXzNcDS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends AkyosUpdates_KernelDevDebugContainer
{
    /**
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'AkyosUpdates\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'AkyosUpdates\\Controller\\GenericWPOptionsController::genericWPOptions' => ['privates', '.service_locator.BSUJTBe.AkyosUpdates\\Controller\\GenericWPOptionsController::genericWPOptions()', 'getGenericWPOptionsControllergenericWPOptionsService', true],
            'AkyosUpdates\\Controller\\HostingController::genericWPOptions' => ['privates', '.service_locator...gTWQr.AkyosUpdates\\Controller\\HostingController::genericWPOptions()', 'getHostingControllergenericWPOptionsService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'AkyosUpdates\\Controller\\GenericWPOptionsController:genericWPOptions' => ['privates', '.service_locator.BSUJTBe.AkyosUpdates\\Controller\\GenericWPOptionsController::genericWPOptions()', 'getGenericWPOptionsControllergenericWPOptionsService', true],
            'AkyosUpdates\\Controller\\HostingController:genericWPOptions' => ['privates', '.service_locator...gTWQr.AkyosUpdates\\Controller\\HostingController::genericWPOptions()', 'getHostingControllergenericWPOptionsService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'AkyosUpdates\\Kernel::registerContainerConfiguration' => '?',
            'AkyosUpdates\\Controller\\GenericWPOptionsController::genericWPOptions' => '?',
            'AkyosUpdates\\Controller\\HostingController::genericWPOptions' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'AkyosUpdates\\Controller\\GenericWPOptionsController:genericWPOptions' => '?',
            'AkyosUpdates\\Controller\\HostingController:genericWPOptions' => '?',
        ]));
    }
}
