<?php

namespace ContainerCXzNcDS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenericWPOptionsServiceService extends AkyosUpdates_KernelDevDebugContainer
{
    /**
     * Gets the public 'AkyosUpdates\Service\GenericWPOptionsService' shared autowired service.
     *
     * @return \AkyosUpdates\Service\GenericWPOptionsService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/GenericWPOptionsService.php';

        return $container->services['AkyosUpdates\\Service\\GenericWPOptionsService'] = new \AkyosUpdates\Service\GenericWPOptionsService();
    }
}
