<?php

namespace ContainerCXzNcDS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHostingControllergenericWPOptionsService extends AkyosUpdates_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator...gTWQr.AkyosUpdates\Controller\HostingController::genericWPOptions()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator...gTWQr.AkyosUpdates\\Controller\\HostingController::genericWPOptions()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'hostingService' => ['services', 'AkyosUpdates\\Service\\HostingService', 'getHostingServiceService', true],
        ], [
            'hostingService' => 'AkyosUpdates\\Service\\HostingService',
        ]))->withContext('AkyosUpdates\\Controller\\HostingController::genericWPOptions()', $container);
    }
}
