<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUmgQ1Iw\AkyosUpdates_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUmgQ1Iw/AkyosUpdates_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUmgQ1Iw.legacy');

    return;
}

if (!\class_exists(AkyosUpdates_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUmgQ1Iw\AkyosUpdates_KernelDevDebugContainer::class, AkyosUpdates_KernelDevDebugContainer::class, false);
}

return new \ContainerUmgQ1Iw\AkyosUpdates_KernelDevDebugContainer([
    'container.build_hash' => 'UmgQ1Iw',
    'container.build_id' => '531f15dc',
    'container.build_time' => 1727447785,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUmgQ1Iw');
